### ISSUE TITLE
Crash when Augment interacts with Botany Pots

### ISSUE THREAD

**Issue by koihei** [refinedmods/refinedpipes#101]
### Describe the bug

Botany Pots and Botany Hopper Pots will connect with Refined Pipes but nothing will happen.
If an extractor pipe is added the game will crash.
The pots don't need to be setup with farmland/seeds for the crash to happen.

_Not sure if this should be here or on Botany Pots, and I don't think they can interact either way, Botany Hopper Pots behavior is to push items to a storage below it._

https://pastebin.com/LVB5re9Z

Version:
Refined Pipes: 0.5.1
Botany Pots: 7.1.23

### How can we reproduce this bug or crash?

Place a Botany Pot on top of an item pipe and insert an augment.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Pipes version is this happening on?

0.5.1

### Relevant log output

https://pastebin.com/LVB5re9Z

**Comment by JasonKillsUs** [comment]
same here!

**Comment by raoulvdberge** [comment]
This is fixed for 1.18.1 in 1224833c7728c338e47e0acd1c6079e013e90dc2. The fix won't be backported for 1.16.5.

**Comment by raoulvdberge** [comment]
Actually, let's try to get this on 1.16.5. This issue is quite annoying as it makes the world inaccessable.

**Comment by raoulvdberge** [comment]
Fixed in 996593375eccbc78685fd8005ebd96ae45b130cb for MC 1.16.5
