### ISSUE TITLE
Issue (maybe?) doesn't work with vanilla composter

### ISSUE THREAD

**Issue by Sabster** [refinedmods/refinedpipes#21]
I'm using New Beginnings Modpack - and I have a composter (vanilla) that the pipes won't connect too.  I don't know if this was supposed to be this way or not, but in case it doesn't work with any of the other vanilla machines, I figured I'd report it.

refinedpipes-0.4.1.jar

**Comment by bloodscon** [comment]
composters have funny way of showing inventory a few pipe mods have problems with them use hoppers as a go between the composter and your pipes

**Comment by raoulvdberge** [comment]
There is no item handler implemented for vanilla composters. We will not support this block.
