### ISSUE TITLE
Pipes working with Mekanism?

### ISSUE THREAD

**Issue by Daihok41** [refinedmods/refinedpipes#22]
I cant seem to get the pipes to work with mekanism machines. Is this a known issue or am I doing something wrong? I am trying to filter items for processing ore but the machine wont take the items.

**Comment by Darkere** [comment]
Make sure that the items can go in where you are trying to put them by confirming with a vanilla hopper. 

For mekanism side configuration is a concern and also if the output is filled.

**Comment by Daihok41** [comment]
Yea trying to input through the top. Works with vanilla hopper but not the pipe. Right now had to set up 2 diff chests then hopper bottom chest to machine. reason for diff chests am filtering ores in. And yea was using filter but have tryed the pipe with filter and without. Niether would work

**Comment by Darkere** [comment]
Alright then we are going to need more information. Please post screenshots of the entire setup.
