### ISSUE TITLE
Potential Non-Issue With Network Split

### ISSUE THREAD

**Issue by Theking5301** [refinedmods/refinedpipes#23]
Hello!

Feel free to insta-close this issue if it's not a real issue, but I was looking through the code trying to learn from it when I noticed this check here. Should this be checking the origin against the adjacent instead?

https://github.com/refinedmods/refinedpipes/blob/3b89450d533d37b0ea1033dd03558c7af0b52d5f/src/main/java/com/refinedmods/refinedpipes/network/NetworkManager.java#L168

**Comment by Theking5301** [comment]
Made a PR (#25) if this is indeed an issue :D
https://github.com/refinedmods/refinedpipes/pull/25

**Comment by raoulvdberge** [comment]
Thank you!
