### ISSUE TITLE
Filters when move items from pipe to chest

### ISSUE THREAD

**Issue by Summer-94** [refinedmods/refinedpipes#24]
I'm using 0.4.2 version for minecraft 1.15.2.
For now, is this possible to implement the function using what was already have in the mod, so I can filter the items when moving items from pipe to chest?  
Similiar like the extractor, so I can filter the items move from chest to pipe;  I want to also filter the items when moving from pipe to chest, the items which not passing the filter can continue moving in the pipe and go to the next chest.

is this possible to implement the function using what was already has in the mod ?

**Comment by raoulvdberge** [comment]
Yes, this is on the roadmap. #14
