### ISSUE TITLE
Crash (NullPointerException) when using Item pipes

### ISSUE THREAD

**Issue by kurisubrooks** [refinedmods/refinedpipes#27]
Just returned to my base after exploring and I'm greeted with a crash every time I try to load up the world/client. I had no problems with the item pipe before, I was using it successfully up until now.

According to the logs it has to do with rendering the item pipe (which I have placed in my base)
"java.lang.NullPointerException: Tesselating block model"

The crash log is available here;
https://gist.github.com/kurisubrooks/a513d9be6d3d9da3608a6a410d0cc8a1

**Comment by Darkere** [comment]
try without optifine?

**Comment by kurisubrooks** [comment]
Disabling OptiFine made it so I was able to log into the game and remove the pipe. Thank you for the fix. Should I close this or leave it open for you to investigate/fix for other users?

**Comment by raoulvdberge** [comment]
Let's leave this one open.

**Comment by raoulvdberge** [comment]
Fixed by #104 (I think)
