### ISSUE TITLE
Extractors won't pull items from inventory if one item doesn't have a valid destination

### ISSUE THREAD

**Issue by Demex61** [refinedmods/refinedpipes#3]
When extracting an item from a barrel (vanilla) and trying to dump it into a storage drawer controller, if there is not room in the storage drawer system for the item, it does nothing but fill up the logs with a line like this, and then ignores the rest of the items in the barrel (that do have a valid destination) until the problem item is manually dealt with.
[14:36:26] [Server thread/WARN] [co.ra.re.ne.pi.at.ex.ExtractorAttachment/]: No destination found from BlockPos{x=-45, y=229, z=157}

If I manually remove the problem item, or add it to the extractor blacklist, it works without issue. I have confirmed that the block position mentioned (which repeats every time it tries to extract the item), is indeed the extractor.

This is in version 0.4
Please let me know if you need any more details.

**Comment by praetorianAlpha** [comment]
I am experiencing the same issue in the 0.4.1 version.

**Comment by Nicon4454** [comment]
Stil have this issue in 0.5

**Comment by raoulvdberge** [comment]
The difference between this issue and #13 is that:

#13 is about failing when the first item can't be extracted
#3 is about failing when the selected item to extract can't be inserted into the connected inventory

Either way, I think I have a fix that tackles both issues.
