### ISSUE TITLE
Items not pulling from RFToolsUtility Crafter Tier 3

### ISSUE THREAD

**Issue by JakeMoe** [refinedmods/refinedpipes#30]
I've got an RFToolsUtility Crafter Tier 3 with items in the output buffer.  A basic item pipe is attached, with a single oak chest to the right of it.  On the bottom of the pipe is an advanced extractor.  The pipes appear connected properly, but no items seem to want to flow.

Minecraft: 1.15.2
Forge: 31.2.30
RefinedPipes: 0.4.2
RFToolsUtility: 1.15.2-2.1.3

FWIW, the crafter is taking Mystical Agriculture essences for coal, iron, quarty, and diamond and crafting them into their items. These are the four items I'm trying to pipe out of the crafter at the moment.

**Comment by raoulvdberge** [comment]
That is not a  Refined Pipes issue.
