### ISSUE TITLE
Extraction suggestion

### ISSUE THREAD

**Issue by bloodscon** [refinedmods/refinedpipes#33]
maybe on the higher tier extraction modules make it more custom on the extraction mode
so you could have default or cycle
on default the pipe would extract from chest the normal way empty slot 1 then slot 2 and so on
but on cycle mode it will take from slot 1 then on it's next pull will take from slot 2 even if their is something still in slot 1
(xnet does something like this where it round robins on the extract chest,  if you remember to set it i keep forgetting)
Uses for this would be a high speed mining setup / pre ore processing how many times have you watched you ore process or sorting system get stalled due to something coming into slot 1 on a chest just after its cleared (one of the let downs of thermal ducts)

**Comment by raoulvdberge** [comment]
I have no idea what you mean.
