### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by TechkidMC** [refinedmods/refinedpipes#4]
I just installed refined pipes to my modpack and it became unplayable with the mod

I have 4.3 Gb allocated to Mc

**Comment by Darkere** [comment]
How is this a memory issue? 

Post the crash report if you are still having issues.

**Comment by ajruckman** [comment]
We just downloaded the Valhelsia 2 modpack and we noticed that the memory usage was insane. We used VisualVM to profile the client and we found that the `com.raoulvdberge.refinedpipes.render` thread was responsible for **1.3 GBs** of objects in memory. Here are some screenshots: [https://imgur.com/a/vHWuweX](https://imgur.com/a/vHWuweX)

We measured from a client connected to a remote server. We tested in a new world with 0 placed Refined Pipes anywhere. We never even had them in our inventory. 

Notice the second screenshot... there are over 1.9 million (!) instances of `PipeBakedModel`s in that thread.

This isn't the kindof thing you can submit a crash report for. We have move RAM than the game is using so the game isn't crashing, and even if we didn't have the RAM, a crash report would just say that the JVM ran out of memory. 

I don't pretend to understand how this mod works or how to render things in MC but it seems like that is a problem... We are going to try to do some more investigating though. Thanks!

**Comment by raoulvdberge** [comment]
Thank you, this is actionable and helpful.

**Comment by raoulvdberge** [comment]
This has been fixed for v0.4.2.
