### ISSUE TITLE
Allow pushing items or fluids into pipes

### ISSUE THREAD

**Issue by Random832** [refinedmods/refinedpipes#40]
Various mods (for example Thermal Expansion) are designed to be configurable to automatically output items or fluids to connected pipes or inventories without requiring an extractor equivalent. These currently do nothing when a Refined Pipes pipe is attached.

**Comment by Recaiden** [comment]
I was surprised to see that even hoppers could not input into item pipes.

**Comment by raoulvdberge** [comment]
You would be able to exceed the extraction limit if external mods were able to interact with Refined Pipes pipes.
