### ISSUE TITLE
MC1.15 version 0.4.2 - crash in ExtractorAttachment

### ISSUE THREAD

**Issue by sibomots** [refinedmods/refinedpipes#41]
Crash with error on (marked *here*) line in `ExtractorAttachment.java`

```java
        TileEntity tile = pipe.getWorld().getTileEntity(destinationPos);    // here
        if (tile == null) {
            return;
        }
```

Error log: https://hastebin.com/avoraduqaz.properties

This is not isolated but a repeated issue on the line mentioned.   Do you have some suggestion for a patch?

Let me know if you need more information.

Environment:
Ubuntu Linux, Java-8, dedicated server.
List of mods in crash-report.

**Comment by raoulvdberge** [comment]
1.15 is not supported.

**Comment by raoulvdberge** [comment]
Also note that watchdog crashes don't give a good indication of the cause of the crash, they just print the current stack frame.

**Comment by sibomots** [comment]
OK.  Fair enough.  Thanks for taking a look.
