### ISSUE TITLE
net.minecraft.crash.ReportedException: Tesselating block model

### ISSUE THREAD

**Issue by Sunekaer** [refinedmods/refinedpipes#44]
Issue: Rendering error resulting in invisible pipe when attaching Basic Extractor Attachment to any of the Refined Pipes item or fluid pipes.
Log: https://paste.feed-the-beast.com/view/578ac263
Optifine: no

refinedpipes-0.5.jar
CodeChickenLib-1.16.4-3.5.0.398-universal.jar
1.16.4 35.1.13

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/15

**Comment by raoulvdberge** [comment]
I cannot reproduce this issue. The error indicates that the model wasn't able to load properly.

**Comment by raoulvdberge** [comment]
This is with just Refined Pipes. Did you try without CCL?

**Comment by Sunekaer** [comment]
Ill see if i can reproduce it, issue is that I load the game 100 times without it happens and then suddenly it happens
I have also gotten this error on your Disk Drive from RS https://paste.feed-the-beast.com/view/raw/04c73d50

**Comment by Sunekaer** [comment]
After a lot of restarts and joining the world 
https://paste.sunekaer.com/olititemen.php

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/110207834-3849a500-7e86-11eb-9174-a4a8008461b7.png)
This is what is my world btw
