### ISSUE TITLE
[1.16.4 - 0.5]Network is null Server Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [refinedmods/refinedpipes#45]
Modpack: Direwolf 20 v 1.2.0
Mod Version Refined Pipes 0.5.jar
Minecraft Version 1.16.4

https://pastebin.com/Dr6w7pjV

This happened after an interaction with Building Gadgets the builder, I tried to place the pipes with the tool, since they are all placed at the same time this error happened, I had to remove the mod completely because the issue would come back. I tried to remove the pipes via commands, I removed the mod, placed blocks in the spot the pipes were, and readded, it seems like this is something different that I couldn't really fix. Thanks for looking into it.

**Comment by PossesiveGamer** [comment]
> Modpack: Direwolf 20 v 1.2.0
> Mod Version Refined Pipes 0.5.jar
> Minecraft Version 1.16.4
> 
> https://pastebin.com/Dr6w7pjV
> 
> This happened after an interaction with Building Gadgets the builder, I tried to place the pipes with the tool, since they are all placed at the same time this error happened, I had to remove the mod completely because the issue would come back. I tried to remove the pipes via commands, I removed the mod, placed blocks in the spot the pipes were, and readded, it seems like this is something different that I couldn't really fix. Thanks for looking into it.

I have experienced this as well in a single player world and I went into the server data and removed the refinedpipes-network.data and did exactly what you did and I still crash on load. If I remove the mod I load in fine but then recipes for the modpack im playing mess up because theyre required in some recipes. Im playing Stacia Expert Mode using refined pipes 0.5.

**Comment by Pquemis** [comment]
I play an Aternos server with the modpack Direwolf20 1.16 version1.13.0.mod version refinedpipes-0.5.1.jar    
I have the same log ( https://pastebin.com/c2aVvtUq ). 
Being a modpack, I can't delete or modify the mod. 
mod version refinedpipes-0.5.1.jar

**Comment by raoulvdberge** [comment]
Thanks for the report, but there are no reproduction steps for me to do anything with...
