### ISSUE TITLE
Ex Nihilo Sequentia Compatibility Issue

### ISSUE THREAD

**Issue by Recaiden** [refinedmods/refinedpipes#50]
When an item pipe's destination is broken while items are in transit, it can corrupt nearby Ex Nihilo barrels in some way such that their recipes now produce Air instead of the intended item.
Restarting fixes the recipes.

**Comment by raoulvdberge** [comment]
Have you reported this to Ex Nihilo Sequentia? This doesn't seem like a Refined Pipes issue.

**Comment by Recaiden** [comment]
Yes.

**Comment by raoulvdberge** [comment]
Can you link me the issue?
