### ISSUE TITLE
Saplings (or similar) wont decrease when extracting to Ex Nihilo Barrel

### ISSUE THREAD

**Issue by remplerus** [refinedmods/refinedpipes#55]
**Describe the bug**
When inserting items with external mods pipes the item isn't extracted from the inventory.

**To Reproduce**
_Steps to reproduce the behavior:_

1. Place Barrel
2. Place a item pipe beside the barrel
3. Place a chest beside the pipe.
4. Then when the barrel is filling nothing is getting extracted from the chest, if there is e.g. more than one sapling.

_Expected behavior_
Sapling should be reduced by one each time a sapling is getting transfered to the barrel

**Version:**
Minecraft Version: 1.16.5
Forge Version: 36.0.46
Ex Nihilo: Sequentia Version: 1.16-2.0.2.3
Refined Pipes Version: 0.5

**Comment by Darkosto** [comment]
I am also experiencing this issue. I checked a variety of pipes and item transport mods/methods and Refined Pipes was the only mod having the issue. Just a quick setup can net infinite dirt from only 2 leave blocks. I am running the same versions OP. Any chance this could be looked into?

Thanks!

**Comment by tyler489** [comment]
This also occurs with mekanism pipes it's a bug in ex nihilo I believe I read

**Comment by remplerus** [comment]
Ex nihilo fixed it in dev build, but refined pipes doesnt do anything atm

**Comment by raoulvdberge** [comment]
Probably a Ex Nihilo issue?
