### ISSUE TITLE
New Item Filter

### ISSUE THREAD

**Issue by Cicopath** [refinedmods/refinedpipes#60]
Make a new item filter that connects to the end of a pipe that only allows specific items through. We have an extractor, now why not a separate item that filters out items in the same pipe line? Like, let's say I have an extractor, whitelisted to only Diamonds, Emeralds, and Gold. Since they're all in the same pipe, I need a filter. Diamonds only in this chest, Emeralds in this one, and Gold in this one, rather than them all being put in one chest due to being unfiltered.

**Comment by raoulvdberge** [comment]
check other issues first before creating a new one
