### ISSUE TITLE
Thermal Foundation furnace won't extract

### ISSUE THREAD

**Issue by Cicopath** [refinedmods/refinedpipes#61]
I'm making an automated farm using bees from Productive bees, and when centrifuged, gives me gold/iron dust. The dust is able to be inserted into the furnace, but when the redstome furnace has an Output slot for the gold to be outputted, it doesn't exit the furnace and enter the pipe. It just sits in the furnace.
![2021-03-29_14 09 57](https://user-images.githubusercontent.com/61031176/112880503-83776200-9098-11eb-89c8-9ac209538296.png)
![2021-03-29_14 10 08](https://user-images.githubusercontent.com/61031176/112880504-840ff880-9098-11eb-942c-c1307592c72d.png)

**Comment by raoulvdberge** [comment]
missing extractor
