### ISSUE TITLE
how to use energy pipes?

### ISSUE THREAD

**Issue by Anhilowasntavailabewhotookit** [refinedmods/refinedpipes#65]
they dont do anything on their own, and i cant attach an extractor to them.

**Comment by twothe** [comment]
Technically you just place them down, but they seem to be broken entirely.

**Comment by raoulvdberge** [comment]
They work like any other energy pipe, RF is push-based. This means that energy needs to be injected by an external block (like a generator) and the pipes will auto-eject energy.

**Comment by twothe** [comment]
> They work like any other energy pipe, RF is push-based. This means that energy needs to be injected by an external block (like a generator) and the pipes will auto-eject energy.

No they won't, they break after some time and don't work at all anymore.
