### ISSUE TITLE
One to many

### ISSUE THREAD

**Issue by Knito58** [refinedmods/refinedpipes#66]
Silly question:

How would I setup this to extract from one barrel (Accelerator mod fisherman's barrel) to multiple chests (enchanted books, weapons per type, boots and such)

All I have achieved so far is getting everything nicely filtered into one single chest.

Would I setup a filter to get the unwanted items from said chest into another and so scraping away one after the other unwanted things until everything is in it's own chest?

**Comment by raoulvdberge** [comment]
Questions go on discord.
