### ISSUE TITLE
Cannot sepperate pipes

### ISSUE THREAD

**Issue by LenaCupid** [refinedmods/refinedpipes#71]
Sorry, i don't know where to post this, but is there any way to make two different pipes or pipes with certain blocks not connect like i can with the wrench in Thermal Dynamics or Mekanism?

I stumbled upon this mod as a replacement for Thermal Dynamics but now i actually prefer it due to it's simplicity, it would just be great for management if i could make pipes not connect^^

**Comment by raoulvdberge** [comment]
Duplicate #17
