### ISSUE TITLE
Integrated inventory-extractor attachment

### ISSUE THREAD

**Issue by AliveDevil** [refinedmods/refinedpipes#8]
It'd be nice to have a pipe attachment which has an integrated inventory in order to get items from blocks that only work if there is an inventory available.
The pipes could then be fed into a RefinedStorage importer, for more processing, not requiring thousands of interfaces on e.g. https://github.com/thraaawn/BonsaiTrees or https://github.com/Darkhax-Minecraft/BotanyPots.

Possible configurations:
BasicInventoryAttachment: BasicExtractorAttachment with Chest
ImprovedInventoryAttachment: ImprovedExtractorAttachment with Chest, or BasicInventoryAttachment with ImprovedExtractorAttachment recipe.
Advanced, Elite and Ultimate work the same as Improved.

Each tier might limit the number of _unique_ items and their internally stored quantity. There should not be any manual access to the attachments inventory possible.
All inventory attachments work the same as their extractor attachment counterpart - with filtering removed.

The UI/Waila-tooltip could print how many items of each type there are in the attachment to be transported away.

**Comment by raoulvdberge** [comment]
No, sorry.
