### ISSUE TITLE
Energy Pipes aren't taking RF from Thermal Series Energy Cell, though they once did

### ISSUE THREAD

**Issue by NoTelefragPlz** [refinedmods/refinedpipes#81]
Auto-Output is Enabled. Redstone Control set to Ignored.
![idk](https://user-images.githubusercontent.com/17153137/135736285-30c2c0ed-6cb7-4a0e-b48a-394e13e8680e.PNG)

**Comment by utybo** [comment]
I can confirm, I'm having the same issue, despite this being flagged as "can't reproduce".
