### ISSUE TITLE
crash during server start

### ISSUE THREAD

**Issue by SkinHeadBaby** [refinedmods/refinedpipes#83]
Me and 2 friend are playing on direwolf20 1.16 pack.
I'm not sure why but recently the server started crashing while starting saying that 1 tick took more than 60 seconds and closes, if i disable this setting in the server config the server starts but is not responsive and eveyone times out when trying to log in.
Lately we aren't too active so it happens when there is no one around.
The only way i found to fix it so far is to either disable refined pipes or restore a world backup which is why i'm guessing its refines pipes that causes this or some conflict with a mod maybe not sure.
This is the crash log.
https://pastebin.com/X8cy3pkd

**Comment by raoulvdberge** [comment]
Hi, increase the max tick size in the config. I can't reproduce this.

**Comment by SkinHeadBaby** [comment]
well we will start over i guess
also i did say that when i set the server tick size to -1 the server cant be logged on and everyone times out when trying to log in
